export const pruebasData = [
  {
    "id": "cmq3vt2li000l3s8w14e8mo3n",
    "codigo": "QS-AUR",
    "nombre": "ACIDO URICO",
    "precioUSD": "2.5",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "3.5 - 7.5",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt38e000n3s8w90l593ai",
    "codigo": "QS-AMI",
    "nombre": "AMILASA",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "U/L",
    "valoresReferencia": "Hasta 140",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt3rk000p3s8w0k7c09s1",
    "codigo": "QS-COL",
    "nombre": "COLESTEROL TOTAL",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Menor de 150",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt4ty000t3s8wc7w0zwsw",
    "codigo": "QS-CAL",
    "nombre": "CALCIO",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "8.5 - 11.0",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt5d4000v3s8ww7og1yqc",
    "codigo": "QS-CALI",
    "nombre": "CALCIO IONICO",
    "precioUSD": "4",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "4.6 - 5.3",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt5w7000x3s8w4h32fsqx",
    "codigo": "QS-CRE",
    "nombre": "CREATININA",
    "precioUSD": "2",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Hombres 0.7 - 1.63 Mujeres 0.5 - 1.1",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "6",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt6f7000z3s8wa27im84u",
    "codigo": "QS-CLO",
    "nombre": "CLORO",
    "precioUSD": "4",
    "margenGanancia": "",
    "unidades": "mEq/L",
    "valoresReferencia": "96 - 106",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "7",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt7hb00133s8wac2rq6cu",
    "codigo": "QS-FIB",
    "nombre": "FIBRINOGENO",
    "precioUSD": "4.5",
    "margenGanancia": "",
    "unidades": "%",
    "valoresReferencia": "200 - 450",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "8",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt80c00153s8we420sads",
    "codigo": "QS-FOS",
    "nombre": "FOSFORO",
    "precioUSD": "2.5",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Adultos 2.5 - 4.5 Niños 4.0 - 7.0",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "9",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt8jf00173s8wqo6fxutf",
    "codigo": "QS-FA",
    "nombre": "FOSFATASAS ALCALINAS",
    "precioUSD": "4.5",
    "margenGanancia": "",
    "unidades": "UI/L",
    "valoresReferencia": "Adultos 40 - 140",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "10",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt92j00193s8wloa4esdf",
    "codigo": "QS-GLU",
    "nombre": "GLUCOSA BASAL (AYUNO)",
    "precioUSD": "2",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "70 - 110",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "11",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vt9ln001b3s8w29mdgd1i",
    "codigo": "QS-GPC30",
    "nombre": "GLUCOSA POST CARGA 30 MIN",
    "precioUSD": "2",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "12",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vta4l001d3s8wmt9owxbp",
    "codigo": "QS-GPC60",
    "nombre": "GLUCOSA POST CARGA 60 MIN",
    "precioUSD": "2",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "13",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtann001f3s8wn7a0u5rf",
    "codigo": "QS-GPC120",
    "nombre": "GLUCOSA POST CARGA 120 MIN",
    "precioUSD": "2",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "14",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtb6n001h3s8wz7hxlggj",
    "codigo": "QS-GGT",
    "nombre": "GAMMA GLUTAMIL TRANSFERASA (GGT)",
    "precioUSD": "4.5",
    "margenGanancia": "",
    "unidades": "U/L",
    "valoresReferencia": "5 - 40",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "15",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtbpq001j3s8w2bjc9fym",
    "codigo": "QS-HBA1C",
    "nombre": "HEMOGLOBINA GLICADA (HBA1C)",
    "precioUSD": "10",
    "margenGanancia": "",
    "unidades": "%",
    "valoresReferencia": "Normal menor a 5.7",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "16",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtc8p001l3s8wvyxnvxxv",
    "codigo": "QS-FE",
    "nombre": "HIERRO SERICO",
    "precioUSD": "4",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Hombres 65 - 175 Mujeres 50 - 175",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "17",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtcrr001n3s8wrpvsw38h",
    "codigo": "QS-INS",
    "nombre": "INSULINA BASAL (AYUNAS)",
    "precioUSD": "6.5",
    "margenGanancia": "",
    "unidades": "mg/mL",
    "valoresReferencia": "2 - 25",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "18",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtdas001p3s8wzhzi3kb6",
    "codigo": "QS-INSP",
    "nombre": "INSULINA POSPRANDIAL (2 HORAS)",
    "precioUSD": "6.5",
    "margenGanancia": "",
    "unidades": "mg/mL",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "19",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtdtt001r3s8wjylgoxyf",
    "codigo": "QS-LDH",
    "nombre": "LACTATO DESHIDROGENASA (LDH)",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "UI/L",
    "valoresReferencia": "105 - 333",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "20",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtecv001t3s8w06kr3sfj",
    "codigo": "QS-MG",
    "nombre": "MAGNESIO",
    "precioUSD": "7",
    "margenGanancia": "",
    "unidades": "mEq/dL",
    "valoresReferencia": "1.7 - 2.2",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "21",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtezr001v3s8w3shvxii8",
    "codigo": "QS-NTBNP",
    "nombre": "NT-PRO BNP",
    "precioUSD": "17",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Menor a 125",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "22",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtfit001x3s8wasfvlbyh",
    "codigo": "QS-K",
    "nombre": "POTASIO",
    "precioUSD": "6.5",
    "margenGanancia": "",
    "unidades": "mEq/dL",
    "valoresReferencia": "3.5 - 5.2",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "23",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtg1y001z3s8w467rwwnq",
    "codigo": "QS-PCR",
    "nombre": "PROTEINA C REACTIVA (PCR)",
    "precioUSD": "6.5",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Menor 0.6",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "24",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtgl900213s8wixv0jrbm",
    "codigo": "QS-TG",
    "nombre": "TRIGLICERIDOS",
    "precioUSD": "4.5",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Menor a 136",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "25",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vth4f00233s8w2329di74",
    "codigo": "QS-URE",
    "nombre": "UREA",
    "precioUSD": "2",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "10 - 40",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "26",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq3vtips00273s8wp5hk2few",
    "codigo": "QS-BILT",
    "nombre": "BILIRRUBINA TOTAL",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "0.1 - 1.2 mg/dL",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq3vti6o00253s8wvplzq8sb"
  },
  {
    "id": "cmq3vtj8u00293s8w248ssbe5",
    "codigo": "QS-BILD",
    "nombre": "BILIRRUBINA DIRECTA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "0.0 - 0.4 mg/dL",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq3vti6o00253s8wvplzq8sb"
  },
  {
    "id": "cmq3vtjs1002b3s8wj5o1frxs",
    "codigo": "QS-BILI",
    "nombre": "BILIRRUBINA INDIRECTA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "0.1 - 1.0 mg/dL",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq3vti6o00253s8wvplzq8sb"
  },
  {
    "id": "cmq3vtld3002f3s8wyp3esjaq",
    "codigo": "QS-PROT",
    "nombre": "PROTEINAS TOTALES",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "g/dL",
    "valoresReferencia": "6.0 - 8.0 g/dL",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq3vtku2002d3s8wdunm8mfe"
  },
  {
    "id": "cmq3vtlw7002h3s8w6anxjr8d",
    "codigo": "QS-ALB",
    "nombre": "ALBUMINA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "g/dL",
    "valoresReferencia": "3.0 - 5.0 g/dL",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq3vtku2002d3s8wdunm8mfe"
  },
  {
    "id": "cmq3vtmf7002j3s8wja31xzav",
    "codigo": "QS-GLOB",
    "nombre": "GLOBULINAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "g/dL",
    "valoresReferencia": "2.0 - 4.0 g/dL",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq3vtku2002d3s8wdunm8mfe"
  },
  {
    "id": "cmq3vto53002n3s8wl8afys0e",
    "codigo": "QS-ALT",
    "nombre": "PIRUVICA (ALT)",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "U/L",
    "valoresReferencia": "4 - 36 U/L",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq3vtnh7002l3s8wbijg5rmh"
  },
  {
    "id": "cmq3vtoo5002p3s8w891ya2ef",
    "codigo": "QS-AST",
    "nombre": "OXALOACETICA (AST)",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "U/L",
    "valoresReferencia": "8 - 33 U/L",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq3vtnh7002l3s8wbijg5rmh"
  },
  {
    "id": "cmq415fcs0002ky046ea8hywc",
    "codigo": "COL-T",
    "nombre": "COLESTEROL TOTAL",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Menor de 150",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq415fcs0001ky04fyupwk7z"
  },
  {
    "id": "cmq415fcs0003ky04onfpd2i9",
    "codigo": "COL-HDL",
    "nombre": "COLESTEROL HDL",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Hombres  26 - 63\nMujeres    33- 75",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq415fcs0001ky04fyupwk7z"
  },
  {
    "id": "cmq419sth0004ky04u5m8gzfw",
    "codigo": "COL-LDL",
    "nombre": "COLESTEROL LDL",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Menor de 100",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq415fcs0001ky04fyupwk7z"
  },
  {
    "id": "cmq41biq00005ky0476bui0i4",
    "codigo": "COL-VLDL",
    "nombre": "COLESTEROL VLDL",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "2 - 30",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq415fcs0001ky04fyupwk7z"
  },
  {
    "id": "cmq41dr2w0006ky04yd4w8q2q",
    "codigo": "TG",
    "nombre": "TRIGLICERIDOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Menor de 150",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq415fcs0001ky04fyupwk7z"
  },
  {
    "id": "cmq41shdn0000ld04u1nlicgd",
    "codigo": "QS-NA",
    "nombre": "SODIO",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "mEq/L",
    "valoresReferencia": "135 -  155",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "27",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq43e9k70003kw04tr1octue",
    "codigo": "QS-VDRL",
    "nombre": "VDRL",
    "precioUSD": "3.5",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "28",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq43e9k70004kw04k3g8779x",
    "codigo": "QS-CK",
    "nombre": "CREATIN FOSFOQUINASA (CKTOTAL)",
    "precioUSD": "7",
    "margenGanancia": "",
    "unidades": "U/L",
    "valoresReferencia": "30 - 170",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "29",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq43e9k70005kw04biaefeha",
    "codigo": "QS-CKMB",
    "nombre": "CREATIN FOSFOQUINASA (CKMB)",
    "precioUSD": "12",
    "margenGanancia": "",
    "unidades": "U/L",
    "valoresReferencia": "Menor de 25",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "30",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq453p5b0000l804nggznche",
    "codigo": "QS-LIP]",
    "nombre": "LIPASA",
    "precioUSD": "5.5",
    "margenGanancia": "",
    "unidades": "U/L",
    "valoresReferencia": "Hasta 160",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "31",
    "subcategoriaId": "cmq3vszy2000b3s8wmpuireuz"
  },
  {
    "id": "cmq45knhv0002kz043pkkulse",
    "codigo": "QU-CA",
    "nombre": "CALCIO EN ORINA PARCIAL",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "2 - 18",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq45knhv0003kz04moffud1h",
    "codigo": "QU-FOS",
    "nombre": "FOSFORO EN ORINA PARCIAL",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "20 - 60",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq45r8gr0004kz046pylld6l",
    "codigo": "QU-AU",
    "nombre": "ACIDO URICO EN ORINA PARCIAL",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "7 - 50",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq45r8gr0005kz04bocpwzyp",
    "codigo": "QU-CREA",
    "nombre": "CREATININA EN ORINA PARCIAL",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "30 - 125",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq45r8gr0006kz04zs0m7sik",
    "codigo": "QU-NA",
    "nombre": "SODIO EN ORINA PARCIAL",
    "precioUSD": "4",
    "margenGanancia": "",
    "unidades": "mEq/L",
    "valoresReferencia": "54 - 150",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq45r8gr0007kz04ls7jivso",
    "codigo": "QU-K",
    "nombre": "POTASIO EN ORINA PARCIAL",
    "precioUSD": "4",
    "margenGanancia": "",
    "unidades": "mEq/L",
    "valoresReferencia": "20 - 80",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "6",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq45u3hn0000la04ljxj9735",
    "codigo": "QU-PT",
    "nombre": "PROTEINAS EN ORINA PARCIAL",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/dL",
    "valoresReferencia": "Menor de 25",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "7",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46a7sr0002l704ns2ftuy8",
    "codigo": "QU-PESO",
    "nombre": "PESO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "kg",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq46a7sr0001l7044au5kz8o"
  },
  {
    "id": "cmq46a7sr0003l704fiic52z8",
    "codigo": "QU-TALLA",
    "nombre": "TALLA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "cm",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq46a7sr0001l7044au5kz8o"
  },
  {
    "id": "cmq46a7sr0004l704puwj248c",
    "codigo": "QU-VT",
    "nombre": "VOLUMEN TOTAL 24 HORAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "ml",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq46a7sr0001l7044au5kz8o"
  },
  {
    "id": "cmq46a7sr0005l704x50lqr2s",
    "codigo": "QU-VMC",
    "nombre": "VOLUMEN MINUTO CORREGIDO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq46a7sr0001l7044au5kz8o"
  },
  {
    "id": "cmq46a7sr0006l704hieqjxdg",
    "codigo": "QU-SC",
    "nombre": "SUPERFICIE CORPORAL CORREGIDA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq46a7sr0001l7044au5kz8o"
  },
  {
    "id": "cmq46a7ss0007l7049jb32lhw",
    "codigo": "QU-CREA24H",
    "nombre": "CREATININA EN ORINA 24 HORAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "g/24 horas",
    "valoresReferencia": "Hombres  1.1 - 2.0\nMujeres    0.01 - 1.33",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "6",
    "subcategoriaId": "cmq46a7sr0001l7044au5kz8o"
  },
  {
    "id": "cmq46a7ss0008l704sfxv6sip",
    "codigo": "QU-DEPU",
    "nombre": "DEPURACION DE CREATININA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mL/min",
    "valoresReferencia": "70 - 110",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "7",
    "subcategoriaId": "cmq46a7sr0001l7044au5kz8o"
  },
  {
    "id": "cmq46oxib0000l704yogmdbl9",
    "codigo": "QU-CREA24H",
    "nombre": "CREATININA EN ORINA 24 HORAS",
    "precioUSD": "4",
    "margenGanancia": "",
    "unidades": "mg/24 horas",
    "valoresReferencia": "HOMBRE 1.1 -  2.0\nMUJER     0.01 - 1.33",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "8",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46oxib0001l704r7lncfev",
    "codigo": "QU-CA24H",
    "nombre": "CALCIO EN ORINA DE 24 HORAS",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/24 horas",
    "valoresReferencia": "50 - 150",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "9",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46oxib0002l7047wkk8uy8",
    "codigo": "QU-FOS24H",
    "nombre": "FOSFORO EN ORINA DE 24 HORAS",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/24 horas",
    "valoresReferencia": "0.3 - 1.0",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "10",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46oxib0003l7040263ytmi",
    "codigo": "QU-AU24H",
    "nombre": "ACIDO URICO EN ORINA DE 24 HORAS",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/24 horas",
    "valoresReferencia": "250 - 750",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "11",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46oxib0004l7042axx0qp6",
    "codigo": "QU-U24H",
    "nombre": "UREA EN ORINA DE 24 HORAS",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "mg/24 horas",
    "valoresReferencia": "3 - 20",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "12",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46oxib0005l7047wo2ln0w",
    "codigo": "QU-NA24H",
    "nombre": "SODIO EN ORINA DE 24 HORAS",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "mEq/24 horas",
    "valoresReferencia": "75 - 200",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "13",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46t7gx0006l704tia59rmh",
    "codigo": "QU-K24H",
    "nombre": "POTASIO EN ORINA DE 24 HORAS",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "mEq/L",
    "valoresReferencia": "40 - 150",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "14",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46t7gx0007l704o8yg4ly2",
    "codigo": "QU-CL24H",
    "nombre": "CLORO EN ORINA DE 24 HORAS",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "mEq/L",
    "valoresReferencia": "110 - 250",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "15",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq46t7gx0008l704ppp1h82e",
    "codigo": "QU-MG24H",
    "nombre": "MAGNESIO EN ORINA DE 24 HORAS",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "mEq/24 horas",
    "valoresReferencia": "50 - 150",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "16",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq470gcl0000jx04th2gwumc",
    "codigo": "QU-VT24H",
    "nombre": "VOLUMEN TOTAL 24 HORAS",
    "precioUSD": "0.1",
    "margenGanancia": "",
    "unidades": "ml",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "17",
    "subcategoriaId": "cmq45knhv0001kz04wcoyyare"
  },
  {
    "id": "cmq4769540002jr04jsofhkdj",
    "codigo": "QU-PTC",
    "nombre": "PROTEINAS TOTALES CUALITATIVAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "TRAZAS,POSITIVO",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq4769540001jr04b9sfnn9r"
  },
  {
    "id": "cmq4769540003jr049t1emg9e",
    "codigo": "QU-VT",
    "nombre": "VOLUMEN TOTAL 24 HORAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "ml",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq4769540001jr04b9sfnn9r"
  },
  {
    "id": "cmq4769540004jr04raxuyhj7",
    "codigo": "QU-PCUANTI",
    "nombre": "PROTEINAS CUANTITATIVAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mg/24 horas",
    "valoresReferencia": "Hasta 125",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq4769540001jr04b9sfnn9r"
  },
  {
    "id": "cmq48bhdq0002l20417cy63mf",
    "codigo": "HE-1",
    "nombre": "HEMOGLOBINA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "g/dL",
    "valoresReferencia": "Hombres  13.5 - 17.5\nMujeres    12.0 - 16.0",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48bhdq0003l2048tc1qqdj",
    "codigo": "HE-2",
    "nombre": "HEMATOCRITO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "%",
    "valoresReferencia": "Hombres 40 - 54\nMujeres   36 -48",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48bhdq0004l204rxi4xvge",
    "codigo": "HE-3",
    "nombre": "GLOBULOS BLANCOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "cel/mm3",
    "valoresReferencia": "5000 - 10.000",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48bhdq0005l204iama09cr",
    "codigo": "HE-4",
    "nombre": "PLAQUETAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "cel/mm3",
    "valoresReferencia": "150.000 -400.000",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48bhdq0006l204m4ot1ntp",
    "codigo": "HE-5",
    "nombre": "RECUENTO DIFERENCIAL",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "%",
    "valoresReferencia": "Segmentados Neutrofilos 50 -70\nSegmentados Eosinofilos 1 - 4\nSegmentados Basofilos     0 - 1 \nLinfocitos 20 - 40\nMonocitos   2 - 8",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48l6fm0000l404vwfuyo2q",
    "codigo": "HE-6",
    "nombre": "GLOBULOS ROJOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "millones /mm3",
    "valoresReferencia": "Hombres 4.7 - 6.1\nMujeres   4.2 - 5.4",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "6",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48l6fm0001l404lkrh8wu2",
    "codigo": "HE-7",
    "nombre": "VCM (VOLUMEN CORPUSCULAR MEDIO)",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "fl",
    "valoresReferencia": "80 - 100",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "7",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48l6fm0002l4047nk6pxpq",
    "codigo": "HE-8",
    "nombre": "HCM (HEMOGLOBINA CORPUSCULAR MEDIA)",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "pg",
    "valoresReferencia": "27 - 32",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "8",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48l6fm0003l4043qy15kt8",
    "codigo": "HE-9",
    "nombre": "CHCM (CONCENTRACION DE HEMOGLOBINA CORPUSCULAR MEDIA)",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "g/dl",
    "valoresReferencia": "32 -  36",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "9",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48l6fm0004l4044a1k2fkv",
    "codigo": "HE-10",
    "nombre": "RETICULOCITOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "5",
    "valoresReferencia": "0.5 - 2",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "10",
    "subcategoriaId": "cmq48bhdq0001l204trmuj5tr"
  },
  {
    "id": "cmq48p8p40007l404sf61vqfq",
    "codigo": "HE-1",
    "nombre": "HEMOGLOBINA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "g/dL",
    "valoresReferencia": "Hombres  13.5 - 17.5\nMujeres    12.0 - 16.0",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq48p8p40006l404asnvhzg8"
  },
  {
    "id": "cmq48p8p40008l404hwewmg1j",
    "codigo": "HE-2",
    "nombre": "HEMATOCRITO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "%",
    "valoresReferencia": "Hombres 40 - 54\nMujeres   36 -48",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq48p8p40006l404asnvhzg8"
  },
  {
    "id": "cmq48p8p50009l404qsbjpkmk",
    "codigo": "HE-3",
    "nombre": "GLOBULOS BLANCOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "cel/mm3",
    "valoresReferencia": "5000 - 10.000",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq48p8p40006l404asnvhzg8"
  },
  {
    "id": "cmq48p8p5000al404efgn9bkz",
    "codigo": "HE-5",
    "nombre": "RECUENTO DIFERENCIAL",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "%",
    "valoresReferencia": "Segmentados Neutrofilos 50 -70\nSegmentados Eosinofilos 1 - 4\nSegmentados Basofilos     0 - 1 \nLinfocitos 20 - 40\nMonocitos   2 - 8",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq48p8p40006l404asnvhzg8"
  },
  {
    "id": "cmq48p8p5000bl404dhqgvkwn",
    "codigo": "HE-4",
    "nombre": "PLAQUETAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "cel/mm3",
    "valoresReferencia": "150.000 -400.000",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq48p8p40006l404asnvhzg8"
  },
  {
    "id": "cmq48xw5k000fl404xkgab59m",
    "codigo": "HE-VSG",
    "nombre": "VSG (1 H)",
    "precioUSD": "2",
    "margenGanancia": "",
    "unidades": "mm/h",
    "valoresReferencia": "0 - 20",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq48xw5k000el404ibw8et6n"
  },
  {
    "id": "cmq4923qs000il404wnv0u06n",
    "codigo": "HE-SERIE ROJA",
    "nombre": "GLOBULOS ROJOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq4923qs000hl4046r8jqh7d"
  },
  {
    "id": "cmq4923qs000jl404b9vixko4",
    "codigo": "HE-SERIE BLANCA",
    "nombre": "GLOBULOS BLANCOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq4923qs000hl4046r8jqh7d"
  },
  {
    "id": "cmq4923qs000kl404yhtp7736",
    "codigo": "HE-PLAQUETAS",
    "nombre": "PLAQUETAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq4923qs000hl4046r8jqh7d"
  },
  {
    "id": "cmq49a5ew0002ju04nwzp05rm",
    "codigo": "HE-GRUPO SANGUINEO",
    "nombre": "GRUPO SANGUINEO",
    "precioUSD": "3.5",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "O Rh POSITIVO,A Rh POSITIVO,B Rh POSITIVO,AB Rh POSITIVO,O Rh NEGATIVO,A Rh NEGATIVO,B Rh NEGATIVO,AB Rh NEGATIVO",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq49a5ew0001ju04arehdhrt"
  },
  {
    "id": "cmq49pfqx0002l7044jxzp6gi",
    "codigo": "HOR-T3L",
    "nombre": "T3 (TRIYODOTIRONINA) LIBRE",
    "precioUSD": "7",
    "margenGanancia": "",
    "unidades": "nmol/L",
    "valoresReferencia": "1.2 - 2.7",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq49pfqx0001l704jgwc8z3i"
  },
  {
    "id": "cmq49pfqx0003l704urylsutr",
    "codigo": "HOR-T4L",
    "nombre": "T4 (TIROXINA) LIBRE",
    "precioUSD": "7",
    "margenGanancia": "",
    "unidades": "pmol/L",
    "valoresReferencia": "10.3 -  24.5",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq49pfqx0001l704jgwc8z3i"
  },
  {
    "id": "cmq49vqjf0007l70410mscdhe",
    "codigo": "HOR-TSH",
    "nombre": "TSH (HORMONA ESTIMULANTE DE LA TIROIDES)",
    "precioUSD": "7",
    "margenGanancia": "",
    "unidades": "mUI/L",
    "valoresReferencia": "0.4 - 4.5",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq49pfqx0001l704jgwc8z3i"
  },
  {
    "id": "cmq49xx90000bl704bdtjxz9u",
    "codigo": "T3-L",
    "nombre": "T3 (TRIYODOTIRONINA) LIBRE",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "nmol/L",
    "valoresReferencia": "1.2 - 2.7",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq49xx900009l704tdj4p3vw"
  },
  {
    "id": "cmq49xx90000cl704h7rxy362",
    "codigo": "T4-L",
    "nombre": "T4 (TIROXINA) LIBRE",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "pmol/L",
    "valoresReferencia": "10.3 -  24.5",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq49xx900009l704tdj4p3vw"
  },
  {
    "id": "cmq49xx90000dl704t3imw4pd",
    "codigo": "TSH-1",
    "nombre": "TSH (HORMONA ESTIMULANTE DE LA TIROIDES)",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "mUI/L",
    "valoresReferencia": "0.4 - 4.5",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq49xx900009l704tdj4p3vw"
  },
  {
    "id": "cmq4aeq2a0002ld04vd1278k7",
    "codigo": "HOR-INSB",
    "nombre": "INSULINA BASAL (AYUNAS)",
    "precioUSD": "6.5",
    "margenGanancia": "",
    "unidades": "uUI/mL",
    "valoresReferencia": "5 - 2.5",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq4aeq2a0001ld04z03cv0ia"
  },
  {
    "id": "cmq4aeq2a0003ld04nvozhgg8",
    "codigo": "HOR-INSP",
    "nombre": "INSULINA POSPRANDIAL (2HORAS)",
    "precioUSD": "6.5",
    "margenGanancia": "",
    "unidades": "uUI/mL",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq4aeq2a0001ld04z03cv0ia"
  },
  {
    "id": "cmq4ani5q0002js04du9v8vuf",
    "codigo": "HOR-CORTISOLB",
    "nombre": "CORTISOL BASAL (7 - 9 AM)",
    "precioUSD": "7",
    "margenGanancia": "",
    "unidades": "ug/dL",
    "valoresReferencia": "10 - 20",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq4ani5q0001js04sjkpw9h1"
  },
  {
    "id": "cmq4ani5q0003js04xgd6yq4x",
    "codigo": "HOR-CORTISOLTARDE",
    "nombre": "CORTISOL (3 - 4 PM)",
    "precioUSD": "7",
    "margenGanancia": "",
    "unidades": "ug/dL",
    "valoresReferencia": "3 - 10",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq4ani5q0001js04sjkpw9h1"
  },
  {
    "id": "cmq4b1gtj0002l80438djnlmn",
    "codigo": "PER-PROS",
    "nombre": "PSA TOTAL  (ANTIGENO PROSTATICO ESPECIFICO TOTAL)",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "ng/mL",
    "valoresReferencia": "0.2 - 4.0",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq4b1gtj0001l804ykoa7qn7"
  },
  {
    "id": "cmq4b1gtj0003l804qgwk7o9x",
    "codigo": "PER-PROL",
    "nombre": "PSA LIBRE (ANTIGENO PROSTATICO ESECIFICO LIBRE)",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "ng/mL",
    "valoresReferencia": "0.0 - 0.1",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq4b1gtj0001l804ykoa7qn7"
  },
  {
    "id": "cmq4b1gtj0004l804vfi3mjas",
    "codigo": "PERF-PROSR",
    "nombre": "RELACION PSA LIBRE/PSA TOTAL",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "%",
    "valoresReferencia": "Menor a 25",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq4b1gtj0001l804ykoa7qn7"
  },
  {
    "id": "cmq4ccoic0002jy04ivwasqbx",
    "codigo": "IN-VDRL",
    "nombre": "VDRL",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "NO REACTIVO,REACTIVO 1 dil,REACTIVO 2 dil",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic0003jy044bui8yjb",
    "codigo": "IN-HEPABC",
    "nombre": "HEPATITIS B (ANTI CORE)",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "REACTIVO,NO REACTIVO",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic0004jy04qbr0txl5",
    "codigo": "IN-HEPABA",
    "nombre": "HEPATITIS B (ANTIGENO AUSTRALIA)",
    "precioUSD": "3",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "REACTIVO,NO REACTIVO",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic0005jy04if2t65m4",
    "codigo": "IN-HEPAAG",
    "nombre": "HEPATITIS A  IGG",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "REACTIVO",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic0006jy04i27qqz5l",
    "codigo": "IN-HEPAAM",
    "nombre": "HEPATITIS A IGM",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic0007jy04jfta7xi1",
    "codigo": "IN-HEPAC",
    "nombre": "HEPATITIS C",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "REACTIVO,NO REACTIVO",
    "activa": "true",
    "ordenVisual": "6",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic0008jy04sq7onyan",
    "codigo": "IN-TOX",
    "nombre": "TOXOPLASMOSIS IGG",
    "precioUSD": "4",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "POSITIVO,NEGATIVO",
    "activa": "true",
    "ordenVisual": "7",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic0009jy04ftsjfj9h",
    "codigo": "IN-CHA",
    "nombre": "CHAGAS",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "POSITIVO,NEGATIVO",
    "activa": "true",
    "ordenVisual": "8",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000ajy049lwitigz",
    "codigo": "IN-CITOM",
    "nombre": "CITOMEGALOVIRUS IGM",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "ML",
    "valoresReferencia": "0.5 - 1.8",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "9",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000bjy04o5luhy0f",
    "codigo": "IN-CITOG",
    "nombre": "CITOMEGALOVIRUS IGG",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "ML",
    "valoresReferencia": "0.5 - 1.8",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "10",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000cjy04y7lmts3a",
    "codigo": "IN-EPBG",
    "nombre": "EPSTEIN BARR IGG",
    "precioUSD": "6",
    "margenGanancia": "",
    "unidades": "ML",
    "valoresReferencia": "0.5 -  1.3",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "11",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000djy04k6kgve3r",
    "codigo": "IN-EPBM",
    "nombre": "EPSTEIN BARR IGM",
    "precioUSD": "6",
    "margenGanancia": "",
    "unidades": "ML",
    "valoresReferencia": "0.8 - 3.5",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "12",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000ejy04iz40m62c",
    "codigo": "IN-ANTITG",
    "nombre": "ANTICUERPOS ANTI-TIROGLOBULINA (ANTI-TG)",
    "precioUSD": "10",
    "margenGanancia": "",
    "unidades": "ML",
    "valoresReferencia": "2 - 4",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "13",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000fjy04xrziy1ye",
    "codigo": "IN-ANTITPO",
    "nombre": "ANTICUERPOS ANTI-PEROXIDASA (ANTI-TPO)",
    "precioUSD": "15",
    "margenGanancia": "",
    "unidades": "ML",
    "valoresReferencia": "1",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "14",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000gjy04x6mv7yfb",
    "codigo": "IN-ANA",
    "nombre": "ANTICUERPOS ANTINUCLEARES",
    "precioUSD": "15",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "15",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000hjy04msq83jvj",
    "codigo": "IN-",
    "nombre": "ANTICUERPOS ANTI-ADN",
    "precioUSD": "20",
    "margenGanancia": "",
    "unidades": "ML",
    "valoresReferencia": "8",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "16",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000ijy0420bf4qt8",
    "codigo": "IN-COV",
    "nombre": "COVID-SARS",
    "precioUSD": "8",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "POSITIVO,NEGATIVO",
    "activa": "true",
    "ordenVisual": "17",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000jjy04z1ovqzra",
    "codigo": "IN-DENGUEG",
    "nombre": "DENGUE IGG",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "POSITIVO,NEGATIVO",
    "activa": "true",
    "ordenVisual": "18",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq4ccoic000kjy04238588ky",
    "codigo": "IN-TOXOM",
    "nombre": "TOXOPLASMOSIS IGM",
    "precioUSD": "8",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "POSITIVO,NEGATIVO",
    "activa": "true",
    "ordenVisual": "19",
    "subcategoriaId": "cmq4ccoib0001jy04u3qcftsj"
  },
  {
    "id": "cmq5gk2c40002jo0461k13ma5",
    "codigo": "CO-TPT",
    "nombre": "TPT (TIEMPO PARCIAL DE TROMBOPLASTINA)",
    "precioUSD": "4.5",
    "margenGanancia": "",
    "unidades": "seg",
    "valoresReferencia": "25 - 35",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq5gk2c40001jo049ue1cid9"
  },
  {
    "id": "cmq5gk2c40003jo04uanvo5z4",
    "codigo": "CO-TP",
    "nombre": "TP (TIEMPO DE PROTROMBINA)",
    "precioUSD": "4.5",
    "margenGanancia": "",
    "unidades": "seg",
    "valoresReferencia": "11 - 13.5",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq5gk2c40001jo049ue1cid9"
  },
  {
    "id": "cmq5gk2c40004jo04vuy7nx7r",
    "codigo": "CO-INR",
    "nombre": "INR (INDICE INTERNACIONAL NORMALIZADO)",
    "precioUSD": "2",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "0.8 - 1.2",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq5gk2c40001jo049ue1cid9"
  },
  {
    "id": "cmq5gk2c40005jo04vun87oxs",
    "codigo": "CO-ISI",
    "nombre": "ISI (INDICE DE SENSIBILIDAD INTERNACIONAL)",
    "precioUSD": "0.1",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq5gk2c40001jo049ue1cid9"
  },
  {
    "id": "cmq5gk2c40006jo0416vzfe6z",
    "codigo": "CO-RAZON",
    "nombre": "RAZON",
    "precioUSD": "0.1",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq5gk2c40001jo049ue1cid9"
  },
  {
    "id": "cmq5gmeze0009jo04eocpkncf",
    "codigo": "IN-HIV",
    "nombre": "HIV 1/2",
    "precioUSD": "5",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "POSITIVO,NEGATIVO",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq5gmeze0008jo04j94up87o"
  },
  {
    "id": "cmq5h1l1m0002jj04jv90zakf",
    "codigo": "OR-MACRO",
    "nombre": "ASPECTO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "CLARO,LIGERA TURBIDEZ,TURBIO,MUY TURBIO",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n0003jj04m58pn9cd",
    "codigo": "OR-MAC",
    "nombre": "COLOR",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "AMARILLO CLARO,AMARILLO INTENSO,AMBAR,ROJIZA",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n0004jj04elmdievb",
    "codigo": "OR-MADE",
    "nombre": "DENSIDAD",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "1.010,1.025,1.030,1.020",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n0005jj04lbz8k8bo",
    "codigo": "OR-MAPH",
    "nombre": "PH",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "6.5,7.0,5.0,7.5",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n0006jj04lc05185v",
    "codigo": "OR-MAREA",
    "nombre": "REACCION",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "ACIDA,ALCALINA,NEUTRA",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n0007jj0426idbv2h",
    "codigo": "OR-GLUC",
    "nombre": "GLUCOSA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "NEGATIVO,TRAZAS,POSITIVO",
    "activa": "true",
    "ordenVisual": "6",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n0008jj04b50wj9oo",
    "codigo": "OIR-NI",
    "nombre": "NITRITOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "NEGATIVO,TRAZAS,POSITIVO",
    "activa": "true",
    "ordenVisual": "7",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n0009jj0471yno0hm",
    "codigo": "OR-CE",
    "nombre": "CUERPOS CETONICOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "NEGATIVO,TRAZAS,POSITIVO",
    "activa": "true",
    "ordenVisual": "8",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n000ajj040sailbmt",
    "codigo": "OR-URO",
    "nombre": "UROBILINOGENO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "NEGATIVO,TRAZAS,POSITIVO",
    "activa": "true",
    "ordenVisual": "9",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n000bjj04w98khqxi",
    "codigo": "OR-PROT",
    "nombre": "PROTEINAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "NEGATIVO,POSITIVO,TRAZAS",
    "activa": "true",
    "ordenVisual": "10",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5h1l1n000cjj04dzwnr6l6",
    "codigo": "OR-SANGREMO",
    "nombre": "SANGRE",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "NEGATIVO,TRAZAS,POSITIVO",
    "activa": "true",
    "ordenVisual": "11",
    "subcategoriaId": "cmq5h1l1m0001jj04jnaft9ur"
  },
  {
    "id": "cmq5hdau30002jl043zlv4a77",
    "codigo": "OR-MILEU",
    "nombre": "LEUCOCITOS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq5hdau30001jl047ypgzlk5"
  },
  {
    "id": "cmq5hdau30003jl04nftu5305",
    "codigo": "OR-MICCRIS",
    "nombre": "CRISTALES",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "Acido Urico,Oxalate de Calcio,Uratos amorfos,Fosfatos amorfos,Fosfatos triple,Ausentes",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq5hdau30001jl047ypgzlk5"
  },
  {
    "id": "cmq5hdau30004jl0416ug6fy3",
    "codigo": "OR-MICIL",
    "nombre": "CILINDROS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "Granulosos finos,Granulosos gruesos,Leucocitarios,Hematicos,Ausentes",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq5hdau30001jl047ypgzlk5"
  },
  {
    "id": "cmq5hdau30005jl04zyf3es9t",
    "codigo": "OR-MIBAC",
    "nombre": "BACTERIAS",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "Abundantes,Escasas,Ausentes,Moderadas",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq5hdau30001jl047ypgzlk5"
  },
  {
    "id": "cmq5hdau30006jl04xbmihtc3",
    "codigo": "OR-MICHE",
    "nombre": "HEMATIES",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "",
    "valoresReferencia": "",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq5hdau30001jl047ypgzlk5"
  },
  {
    "id": "cmq5jd22x0002ky04rki0peex",
    "codigo": "HEC-MAA",
    "nombre": "ASPECTO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq5jd22x0001ky04km7ouaxp"
  },
  {
    "id": "cmq5jd22x0003ky04r0sv4f19",
    "codigo": "HEC-MAC",
    "nombre": "COLOR",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "2",
    "subcategoriaId": "cmq5jd22x0001ky04km7ouaxp"
  },
  {
    "id": "cmq5jd22x0004ky04v90i77eb",
    "codigo": "HEC-CON",
    "nombre": "CONSISTENCIA",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "Homogenea,Heterogena",
    "activa": "true",
    "ordenVisual": "3",
    "subcategoriaId": "cmq5jd22x0001ky04km7ouaxp"
  },
  {
    "id": "cmq5jd22x0005ky04yiy1hbvw",
    "codigo": "HEC-MAM",
    "nombre": "MOCO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "Ausente,Presente",
    "activa": "true",
    "ordenVisual": "4",
    "subcategoriaId": "cmq5jd22x0001ky04km7ouaxp"
  },
  {
    "id": "cmq5jd22x0006ky040xqldzac",
    "codigo": "HEC-MAS",
    "nombre": "SANGRE",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "Ausente,Presente",
    "activa": "true",
    "ordenVisual": "5",
    "subcategoriaId": "cmq5jd22x0001ky04km7ouaxp"
  },
  {
    "id": "cmq5jh6hv0009ky04jbm8h192",
    "codigo": "HEC-MIC",
    "nombre": "ANALISIS MICROSCOPICO",
    "precioUSD": "",
    "margenGanancia": "",
    "unidades": "-",
    "valoresReferencia": "-",
    "opcionesPredefinidas": "",
    "activa": "true",
    "ordenVisual": "1",
    "subcategoriaId": "cmq5jh6hv0008ky04vikziuch"
  }
];